#!/usr/bin/env bash

session=$(find ~ ~/work ~/work/itt-mentor-services ~/work/apply-for-teacher-training ~/work/publish-teachet-training ~/.config -mindepth 1 -maxdepth 2 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $session_name -c $session
    exit 0
fi

if ! tmux has-session -t "$session_name" 2> /dev/null; then
  tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
