vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gl", function()
  vim.cmd.Git('log')
end, opts)
vim.keymap.set("n", "<leader>gt", function()
  vim.cmd.Git('stash')
end, opts)

vim.keymap.set("n", "<leader>gb", ":GBrowse<CR>")
vim.keymap.set("v", "<leader>gb", ":GBrowse<CR>")
